test "module states stay small: Mach keeps them (and init copies) on the main thread stack" {
    const std = @import("std");
    // The 8 MB main stack holds every module state twice during Mach's init. Large buffers
    // belong on the heap; these limits catch an inline array creeping back.
    try std.testing.expect(@sizeOf(@import("game/Sandbox.zig")) < 1 << 20);
    try std.testing.expect(@sizeOf(@import("world/World.zig")) < 256 << 10);
    try std.testing.expect(@sizeOf(@import("render/Overlay.zig")) < 4 << 10);
    try std.testing.expect(@sizeOf(@import("ui/Canvas.zig")) < 256 << 10);
}

test {
    _ = @import("character/root.zig");
    _ = @import("character/Ranger.zig");
    _ = @import("engine/Time.zig");
    _ = @import("world/Camera.zig");
    _ = @import("render/Layout.zig");
    _ = @import("city/Routes.zig");
    _ = @import("city/Market.zig");
    _ = @import("machine/Rootsong.zig");
    _ = @import("procedural/Shrine.zig");
    _ = @import("script/Wasm.zig");
    _ = @import("script/Host.zig");
    _ = @import("mod/Mod.zig");
    _ = @import("render/Field.zig");
    _ = @import("engine/Memory.zig");
    _ = @import("procedural/Bridges.zig");
    _ = @import("procedural/Skyline.zig");
    _ = @import("procedural/Mountains.zig");
    _ = @import("procedural/Caves.zig");
    _ = @import("character/Beasts.zig");
    _ = @import("game/Heroes.zig");
    _ = @import("game/Encounters.zig");
    _ = @import("game/Arena.zig");
    _ = @import("procedural/Interiors.zig");
    _ = @import("procedural/Worlds.zig");
    _ = @import("render/Capture.zig");
    _ = @import("asset/Guid.zig");
    _ = @import("asset/Meta.zig");
    _ = @import("asset/Registry.zig");
    _ = @import("asset/Pack.zig");
    _ = @import("asset/Loader.zig");
    _ = @import("asset/HotReload.zig");
    _ = @import("procedural/Seed.zig");
    _ = @import("procedural/Chunk.zig");
    _ = @import("render/Visibility.zig");
    _ = @import("machine/Graph.zig");
    _ = @import("world/ChunkKey.zig");
    _ = @import("world/Streamer.zig");
    _ = @import("procedural/Biome.zig");
    _ = @import("procedural/Scatter.zig");
    _ = @import("engine/FrameStats.zig");
    _ = @import("engine/Flythrough.zig");
    _ = @import("engine/Handle.zig");
    _ = @import("engine/Sky.zig");
    _ = @import("procedural/Terrain.zig");
    _ = @import("procedural/Heightmap.zig");
    _ = @import("procedural/Landscape.zig");
    _ = @import("procedural/TestArbor.zig");
    _ = @import("procedural/Arbor.zig");
    _ = @import("procedural/District.zig");
    _ = @import("machine/Sap.zig");
    _ = @import("asset/Model.zig");
    _ = @import("asset/Gltf.zig");
    _ = @import("asset/Catalog.zig");
    _ = @import("world/Modifications.zig");
    _ = @import("world/World.zig");
    _ = @import("physics/BoxWorld.zig");
    _ = @import("game/Save.zig");
    _ = @import("game/Sandbox.zig");
    _ = @import("game/Build.zig");
    _ = @import("game/Profile.zig");
    _ = @import("game/Avatar.zig");
    _ = @import("game/Player.zig");
    _ = @import("engine/Gamepads.zig");
    _ = @import("engine/PadBindings.zig");
    _ = @import("game/Creator.zig");
    _ = @import("game/Progress.zig");
    _ = @import("game/Dialogue.zig");
    _ = @import("ui/Canvas.zig");
    _ = @import("ui/Menu.zig");
    _ = @import("ui/Screens.zig");
    _ = @import("game/Settings.zig");
    _ = @import("game/PadPreset.zig");
    _ = @import("game/Bindings.zig");
    _ = @import("audio/Synth.zig");
    _ = @import("audio/Mixer.zig");
    _ = @import("audio/Director.zig");
    _ = @import("vehicle.zig");
    _ = @import("vehicle/Designs.zig");
    _ = @import("game/Garage.zig");
    _ = @import("game/Collectibles.zig");
    _ = @import("game/Fabricator.zig");
    _ = @import("vehicle/HiveMeshes.zig");
    _ = @import("game/Enemies.zig");
    _ = @import("game/Combat.zig");
    _ = @import("vehicle/ShipMeshes.zig");
    _ = @import("vehicle/ScalariMeshes.zig");
    _ = @import("game/Skies.zig");
    _ = @import("game/Hangar.zig");
    _ = @import("game/Rig.zig");
    _ = @import("game/Specials.zig");
    _ = @import("combat/Firearms.zig");
    _ = @import("render/Overlay.zig");
    _ = @import("machine/Device.zig");
    _ = @import("machine/Blueprint.zig");
    _ = @import("machine/Machine.zig");
    _ = @import("physics/Rotation.zig");
    _ = @import("physics/Vehicle.zig");
    _ = @import("physics/TriangleMesh.zig");
    _ = @import("combat/CombatSystem.zig");
    _ = @import("game/SuperMobility.zig");
    _ = @import("game/Companion.zig");
    _ = @import("ai/Hive.zig");
}
